import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Web soxovn",
  description: "Generated by create next app",
  icons: "/logo.svg",
  keywords: ["soxovn", "soxokienthiet"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>{children}</body>
    </html>
  );
}
